version: "3.3"

networks:
  default:
    external:
      name: app

services:
  comunion-redis:
    container_name: comunion-redis
    image: redis:alpine
    restart: always

  comunion-account:
    image: ${COMUNION_ACCOUNT_IMAGE}
    container_name: comunion-account
    volumes:
      - /etc/localtime:/etc/localtime
    env_file:
      - ./comunion-conf.env
    environment:
      PG_MASTER: postgres://comunion:comunion2020@localhost:5432/comunion?sslmode=disable&connect_timeout=10&search_path=comunion&timezone=Asia/Shanghai
    depends_on:
      - comunion-redis
    links:
      - comunion-redis
    restart: always

  comunion-cores:
    image: ${COMUNION_CORES_IMAGE}
    container_name: comunion-cores
    volumes:
      - /etc/localtime:/etc/localtime
    env_file:
      - ./comunion-conf.env
    environment:
      PG_MASTER: postgres://comunion:comunion2020@localhost:5432/comunion?sslmode=disable&connect_timeout=10&search_path=comunion&timezone=Asia/Shanghai
    depends_on:
      - comunion-redis
    links:
      - comunion-redis
    restart: always

  comunion-eth:
    image: ${COMUNION_ETH_IMAGE}
    container_name: comunion-cores
    volumes:
      - /etc/localtime:/etc/localtime
    env_file:
      - ./comunion-conf.env
    environment:
      PG_MASTER: postgres://comunion:comunion2020@localhost:5432/comunion?sslmode=disable&connect_timeout=10&search_path=comunion&timezone=Asia/Shanghai
    depends_on:
      - comunion-redis
    links:
      - comunion-redis
    restart: always

  comunion-notification:
    image: ${COMUNION_NOTIFICATION_IMAGE}
    container_name: comunion-cores
    volumes:
      - /etc/localtime:/etc/localtime
    env_file:
      - ./comunion-conf.env
    environment:
      PG_MASTER: postgres://comunion:comunion2020@localhost:5432/comunion?sslmode=disable&connect_timeout=10&search_path=comunion&timezone=Asia/Shanghai
    depends_on:
      - comunion-redis
    links:
      - comunion-redis
    restart: always

  